name: CD Pipeline to Render (staging and production)

on:
  push:
    branches:
      - staging
      - main
  release:
    types: [published]
  workflow_dispatch:

env:
  PORT: 5001
  IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/my-node-app:${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build & Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}

      # Deploy to Render (Production)
      - name: Deploy to Render Production
        if: github.ref == 'refs/heads/main' || (github.event_name == 'release' && github.event.action == 'published')
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"imagePath":"${{ env.IMAGE }}"}' \
            ${{ secrets.RENDER_PROD_DEPLOY_HOOK }}
